---
- name: "python modules, libopenblas-dev, g++, git, unzip"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-numpy
    - python-scipy
    - python-dev
    - python-pip
    - python-nose
    - libopenblas-dev
    - g++
    - git
    - unzip

- name: "numpy, scipy, nose, h5py, Theano, TensorFlow, Keras, spacy, progressbar"
  pip:
    name: "{{ item }}"
  with_items:
    - numpy
    - scipy
    - nose
    - Theano
    - Keras
    - spacy
    - scikit-learn
    - progressbar
    - Cython
    - word2vec
  sudo: no